name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: latest

    - name: Cache uv dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/uv
          .venv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Install dependencies
      run: uv sync

    - name: Run full test suite
      run: uv run pytest tests/ --cov=src --cov-report=xml --cov-report=html --cov-fail-under=65

    - name: Build package
      run: uv build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/

    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      with:
        name: coverage-reports
        path: |
          htmlcov/
          coverage.xml

  quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: latest

    - name: Install dependencies
      run: uv sync

    - name: Run code quality checks
      run: |
        uv run black --check src/ tests/
        uv run ruff check src/ tests/
        uv run ruff format --check src/ tests/

    - name: Check package metadata
      run: |
        uv run python -c "
        import tomllib
        with open('pyproject.toml', 'rb') as f:
            data = tomllib.load(f)
        project = data.get('project', {})
        required_fields = ['name', 'version', 'description', 'authors']
        missing = [f for f in required_fields if not project.get(f)]
        if missing:
            print(f'Missing required fields: {missing}')
            exit(1)
        print('All required fields present')
        "
